name: Build and Upload EXE

on:
  schedule:
    - cron: '0 0 * * 1' 
  push:
    branches:
      - main  # Automatyczne uruchamianie po pushu na mastera
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet pyinstaller
        # Uruchomienie skryptu installResources.ps1
        .\installResources.ps1

    - name: Build EXE
      run: |
        pyinstaller --onefile --name converter converter.py  

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my_application
        path: dist/converter.exe 
